AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  stone-miner

  Sample SAM Template for stone-miner
  
Globals:
  Function:
    Timeout: 120

Resources:
  DigCharacterCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: app.digCharacterCount
      Runtime: nodejs8.10
      Timeout: 600
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 3 * ? *)

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DigCharacterCountFunction:
    Description: "DigCharacterCountFunction ARN"
    Value: !GetAtt DigCharacterCountFunction.Arn
  DigCharacterCountFunctionIamRole:
    Description: "Implicit IAM Role created for DigCharacterCountFunction"
    Value: !GetAtt DigCharacterCountFunctionRole.Arn
